<?php

namespace Sofian\QuranAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LieuRevelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuRevelationRepository extends EntityRepository
{
}
