sofian_quran_app_homepage:
    path:     /
    defaults: { _controller: SofianQuranAppBundle:Default:index}

sofian_quran_app_quran_index:
    path:   /Quran
    defaults: { _controller: SofianQuranAppBundle:Default:quranIndex}

sofian_quran_app_sura:
    path:   /Quran/sura/{suraId}
    defaults: { _controller: SofianQuranAppBundle:Default:quranSura}

sofian_quran_app_populate_suraTitles:
    path:   /Quran/doTheJob
    defaults: { _controller: SofianQuranAppBundle:Default:writeTranslitTitles}